name: Build Android APK
run-name: ${{ github.event.inputs.repository || inputs.repository }} ${{ (github.event.inputs.branchName || inputs.branchName) && format('{0}', github.event.inputs.branchName || inputs.branchName) }} ${{ (github.event.inputs.subdir || inputs.subdir) && format('[/{0}]', github.event.inputs.subdir || inputs.subdir) }} :${{ github.event.inputs.taskName || inputs.taskName }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/android/sunflower"
      authToken:
        description: "Personal Access Token (PAT) / Auth token for private repository [Optional]"
        required: false
        default: ""
      branchName:
        description: "Git branch name [Optional]"
        required: false
        default: ""
      subdir:
        description: "Relative subdirectory path when the project is nested [Optional]"
        required: false
        default: ""
      jdkVersion:
        description: "OpenJDK version (recommended: 17 or 21)"
        required: false
        default: "21"
      taskName:
        description: "build.gradle task name: assembleDebug, assembleRelease, etc."
        required: false
        default: "assembleRelease"
  workflow_call:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        type: string
      authToken:
        description: "Personal Access Token (PAT) / Auth token for private repository [Optional]"
        required: false
        type: string
        default: ""
      branchName:
        description: "Git branch name [Optional]"
        required: false
        type: string
        default: ""
      subdir:
        description: "Relative subdirectory path when the project is nested [Optional]"
        required: false
        type: string
        default: ""
      jdkVersion:
        description: "OpenJDK version (recommended: 17 or 21)"
        required: false
        type: string
        default: "21"
      taskName:
        description: "build.gradle task name: assembleDebug, assembleRelease, etc."
        required: false
        type: string
        default: "assembleRelease"
    secrets:
      authToken:
        description: "Auth token as secret [Optional]"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest # Android SDK is built into this image
    steps:
      - name: Checkout Action Repository
        uses: actions/checkout@v4

      - name: Run APK Builder Action
        uses: ./
        with:
          repository: ${{ github.event.inputs.repository || inputs.repository }}
          authToken: ${{ github.event.inputs.authToken || inputs.authToken || secrets.authToken }}
          branchName: ${{ github.event.inputs.branchName || inputs.branchName }}
          subdir: ${{ github.event.inputs.subdir || inputs.subdir }}
          jdkVersion: ${{ github.event.inputs.jdkVersion || inputs.jdkVersion }}
          taskName: ${{ github.event.inputs.taskName || inputs.taskName }}
